import type { Metadata } from 'next';
import { Geist, Geist_Mono, Lexend } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import { ModeToggle } from '@/components/ModeToggle';
import HorizontalNav from '@/components/HorizontalNav';
import { Toaster } from '@/components/ui/sonner';

import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

const lexend = Lexend({
	variable: '--font-lexend',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					{/* <div className="mb-25"></div> */}
					<HorizontalNav></HorizontalNav>
					{children}
					<Toaster />
					<div className="fixed bottom-0 right-0 p-4">
						<ModeToggle></ModeToggle>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
